all:
  hosts:
    iron:
      ansible_connection: local  
      become_user: ianj
    ash:
      ansible_connection: ssh
      ansible_user: ianj 
      ansible_private_key_file: ~/.ssh/fuji
      ansible_host: 10.0.0.15
      ansible_port: 22