---
- name: Update Iron
  hosts: iron 
  become: yes
  roles:
    - lxd

  tasks:
    # - name: 'update cache and upgrade'
      # apt:
        # upgrade: full
        # update_cache: yes
        # autoremove: yes
 
    - name: "Ash's container profile"
      shell: >
        lxc profile list | awk '/ash/ { print $2 }'
      register: ash_profile_listed
 
    - name: "Create Ash's container profile"
      shell: lxc profile create ash
      when: ash_profile_listed.stdout != 'ash'

    - name: Load Ash's profile
      set_fact:
        ash_profile: "{{ lookup('template', 'lxd-ash-profile.yml.j2') }}"

    - name: Edit Ash's profile
      shell: |
        echo "{{ ash_profile }}" | lxc profile edit ash


    # just seeing if I can avoid the lxd_container module 
    # would probably be better to use it but I need to practise 
    # my shell scripting
    - name: 'Register lxc ls search for ash container'
      shell: >
        lxc ls -c n | awk '/ash/ { gsub(/ /, "", $2); print $2 }'
      register: ash_ls_result

    - name: 'Debug | ash_container_presnt'
      debug:
        msg: "{{ ash_ls_result }}"
        verbosity: 1
        
    - name: 'Create container ash'
      command: 'lxc launch ubuntu:20.04 ash -p default -p ash'
      when: ash_ls_result.stdout != 'ash'
      register: ash_launch_output

    - name: Debug | ash launch output'
      debug:
        msg: "{{ ash_launch_output }}"
        verbosity: 1
      when: ash_ls_result.stdout != 'ash'




